# Generated by Django 5.1 on 2024-08-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('user_role', models.CharField(choices=[('assistant', 'Ассистент'), ('leader', 'Староста'), ('accountant', 'Бухгалтер'), ('helper', 'Помощник')], max_length=20)),
                ('questions', models.TextField()),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('house', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
            ],
        ),
    ]
