# Generated by Django 5.1 on 2024-08-21 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('local_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('varA', models.CharField(max_length=255)),
                ('varB', models.CharField(max_length=255)),
                ('varC', models.CharField(max_length=255)),
                ('varD', models.CharField(max_length=255)),
                ('varE', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='question_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('point', models.IntegerField()),
                ('minimum', models.IntegerField()),
                ('short_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='test_icons/')),
                ('questionsCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('number_of_participants', models.IntegerField()),
                ('payment_date', models.CharField(max_length=50)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('headman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headman_of_house', to='items.user')),
                ('participants', models.ManyToManyField(related_name='houses', to='items.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='items.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_point', models.IntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('card_tasks', models.ManyToManyField(related_name='reports', to='items.cardtask')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='items.user')),
            ],
        ),
        migrations.AddField(
            model_name='cardtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.task'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('accountant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_of_team', to='items.user')),
                ('houses', models.ManyToManyField(related_name='teams', to='items.house')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='items.test'),
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='items.testcategory'),
        ),
        migrations.CreateModel(
            name='WrittenTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_correct_answer', models.IntegerField()),
                ('answers', models.ManyToManyField(related_name='written_tests', to='items.answer')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_tests', to='items.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_tests', to='items.user')),
            ],
        ),
    ]
