# Generated by Django 5.1 on 2024-08-22 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_cardtask_questions_task_test_testcategory_house_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibleCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done')], default='new', max_length=20)),
                ('headman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_carts', to='items.user')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_carts', to='items.house')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done')], default='new', max_length=20)),
                ('date', models.DateField()),
                ('deadline', models.DateField()),
                ('quantity', models.IntegerField()),
                ('amount_left', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsible_cart', models.ManyToManyField(to='items.responsiblecart')),
            ],
        ),
    ]
