# Generated by Django 5.1 on 2024-08-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_responsiblecart_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('student', 'студент'), ('assistant', 'Ассистент'), ('leader', 'Староста'), ('accountant', 'Бухгалтер'), ('helper', 'Помощник')], max_length=20),
        ),
    ]
